### ISSUE TITLE
GUI not launching

### ISSUE THREAD

**Issue by ayush9398** [aerospaceresearch/VisMa#116]
I am new to visma, installed it using `pip3 install visualmath`
After installation I tried `from visma.main import init` but it gives error `cannot import name 'init'
`.
Please help!

**Comment by ZER-0-NE** [comment]
I believe it's `initGUI`.
Take a look [here](https://github.com/aerospaceresearch/visma/wiki#installation) and see if it helps.

**Comment by ayush9398** [comment]
Yeah, it's working now. Thanks.
