### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets' Error while trying to run main.py

### ISSUE THREAD

**Issue by nahimilega** [aerospaceresearch/VisMa#120]
It gives an error with PyQt5 ver 5.12.

![image](https://user-images.githubusercontent.com/42585035/53590141-21955700-3bb7-11e9-8419-3c92d666d4f6.png)

**Comment by nahimilega** [comment]
I would like to take this issue.

**Comment by Alii-Khaled** [comment]
@8hantanu 
I solved the issue by downgrading the PyQt5 version to 5.7.1 due to some issues with PyQt5 with their QtWebEngineWidgets in the latest versions.
i think we can solve it by changing the Requirement.txt file from ( PyQt5>=5 ) to ( PyQt5==5.7.1)

**Comment by 8hantanu** [comment]
The QtWebEngineWidgets is available from PyQt5.6. So any version between 5.6 and 5.11 will suffice.

**Comment by Alii-Khaled** [comment]
I searched more in that issue and found out that QtWebEngineWidgets for versions of PyQt5 (5.12+) can be separately installed using ( pip install PyQtWebEngine 5.12 in order for PyQt5 to work well. 
i tested it using the Requirement.txt & will make a Pull Request for the Requirement file after editing. 
Thx for Help @8hantanu <3

**Comment by nahimilega** [comment]
> @8hantanu
> I solved the issue by downgrading the PyQt5 version to 5.7.1 due to some issues with PyQt5 with their QtWebEngineWidgets in the latest versions.
> i think we can solve it by changing the Requirement.txt file from ( PyQt5>=5 ) to ( PyQt5==5.7.1)

Actually I wanted to fix this issue as it could be a good start for me.

**Comment by Alii-Khaled** [comment]
Oh !! ... i am so sorry, but i really wanted to end this issue cause i couldn't even open the program.
Again .. I am so Sorry @nahimilega . now you can contribute directly without facing unnecessary problems.

**Comment by sidkothiyal** [comment]
Solved with pull request #123
