### ISSUE TITLE
GUI not functioning properly

### ISSUE THREAD

**Issue by vidhanarya** [aerospaceresearch/VisMa#125]
When I try to run visma gui, it gives following warning and gui also doesn't look as expected -

<pre>(aero) <font color="#8AE234"><b>vidhanarya@vidhanarya-MacBookPro</b></font>:<font color="#729FCF"><b>~/Desktop/Project/visma</b></font>$ python3 main.py&gt;&gt;&gt; gui
QLayout: Attempting to add QLayout &quot;&quot; to WorkSpace &quot;&quot;, which already has a layout
</pre>

![issue-visma](https://user-images.githubusercontent.com/28908101/53806107-19039e80-3f72-11e9-884c-649f5a4ee123.png)

One possible reason I could think is while building visma from source, I encountered following error
<pre>(aero) <font color="#8AE234"><b>vidhanarya@vidhanarya-MacBookPro</b></font>:<font color="#729FCF"><b>~/Desktop/Project/visma</b></font>$ python3 main.pyTraceback (most recent call last):
  File &quot;main.py&quot;, line 2, in &lt;module&gt;
    from visma.gui.window import initGUI
  File &quot;/home/vidhanarya/Desktop/Project/visma/visma/gui/window.py&quot;, line 15, in &lt;module&gt;
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named &apos;PyQt5.QtWebEngineWidgets&apos;</pre>

Which was solved by installing PyQt5==5.8.2 instead of using version 5.12 which was installed after <pre>pip3 install -r requirements.txt</pre>

I am using Ubuntu 18.04.2 LTS on MacBook Pro (2017 model)
Also, visma was running fine for me on macOS 10.14 (Although that PyQt5 problem was still there)

**Comment by sidkothiyal** [comment]
Hey @vidhanarya

Thanks for reporting this issue. 
If am not incorrect in understanding the problem, you are facing the described issue on both Ubuntu and macOs, right?

**Comment by vidhanarya** [comment]
I found that I was using the 'master' source, not the 'dev' source in which PyQtWebEngine was added in the requirements, anyway I changed branch from master to dev and then installed required packages. After doing that error still persist, on linux gui is not opening properly as shown in the image from first comment
On macOS, gui was looking as it should (i.e no shrunk input table) just like the gif below
![demo](https://user-images.githubusercontent.com/28908101/53831108-fdb48580-3fa9-11e9-9d3c-339e0aa4d7a3.png)

**Comment by 8hantanu** [comment]
I think the GUI is not working as expected in Linux because of the screen resolution. It must be at least 1300x900.
