### ISSUE TITLE
Visma cannot handle simplifications with multiple parentheses

### ISSUE THREAD

**Issue by vidhanarya** [aerospaceresearch/VisMa#129]
As stated in Issue #78, it was given that "visma cannot calculate fractional powers", I would like to generalise the problem as visma cannot simplify/calculate equations with multiple parentheses such as (4 + (5 + 4))

<pre>(aero) <font color="#8AE234"><b>vidhanarya@macbookpro</b></font>:<font color="#729FCF"><b>visma</b></font>$ python3 main.py
&gt;&gt;&gt; simplify(4^0.571)
INPUT: 2.2038102317532213
OPERATION: simplify
OUTPUT: 2.2038102317532213

2.2038102317532213

&gt;&gt;&gt; simplify(4^(4/7))
Invalid Expression
&gt;&gt;&gt; simplify(4 + 5)
INPUT: 4.0 + 5.0
OPERATION: simplify
OUTPUT: 9.0

4.0 + 5.0

(Adding 5.0 and 4.0)
9.0

&gt;&gt;&gt; simplify(4 + (4 + 1))
Invalid Expression</pre>
Here answer to simplify(4^0.571) is same as simplify(4^(4/7)). One possible solution is checking for number of '(' in 'commandExec' function (cli.py)  and then recursively simplify from the last parentheses such that,
simplify(4 + (4 + (4 + 1))) is
-> simplify(4 + (4 + 5))
-> simplify(4 + 9)
-> INPUT: 13
    OPERATION: simplify
    OUTPUT: 9

**Comment by vidhanarya** [comment]
If the above qualifies as a valid issue and my solution qualify as a valid solution then I would like to implement the same in the visma interface

**Comment by sachinam1397** [comment]
Can you assign me for this issue @vidhanarya

**Comment by mayankDhiman** [comment]
Fixed by #199
