### ISSUE TITLE
Handling cases with multiple parenthesis and expression simplification

### ISSUE THREAD

**Issue by 8hantanu** [aerospaceresearch/VisMa#141]
### To do:
- Use _Expression_ class as token for inputs containing multiple parentheses.
- Simplify the expressions recursively while also updating steps and comments list (#129).

### Expected outcome:
- A bool class property named `reduced` in the Expression class which specifies if the given expression can be further simplified.
- If the expression is simplified to a single token change the class type from _Expression_ to appropriate _Function_ class. For ex: `(x + 2x)` reduces to `3x`, change token type from _Expression_ to _Variable_.
- If the expression is simplified and still contains multiple tokens after simplification, set the `self.reduced` to `true` and update the `self.tokens` with the simplified tokens list. For ex: `(x^2 + x + 2x)` simplifies `(x^2 + 3x)` which is not further reducable, therefore set `self.reduced`  to `true`.
- Simplification methods for expression add/sub/mul/div must be defined. Better to define them as class methods in _Expression_ class.
- Update the steps and its comments at each recursive expression simplification.

Refer the _**io/tokenize.py**_, _**io/simplify.py**_ and _**functions/structure.py**_ modules.

**Edit**: 
Below is what I mean by
>Use _Expression_ class as token for inputs containing multiple parentheses

If input is `1 + 2 * (x + (2x + y))` then
```
Const   Bin   Const   Bin   Expr                           
└─ 1    └─ +  └─ 2    └─ *  └─ [Var   Bin   Expr]
                                └─ x  └─ +  └─ [Var   Bin   Var ]
                                                └─ 2x └─ +  └─ y
```
The tokens list is to be stored in `tokens` property of _Expression_.

**Comment by mayankDhiman** [comment]
fixed by #199
