### ISSUE TITLE
Plot in both 2D and 3D

### ISSUE THREAD

**Issue by 8hantanu** [aerospaceresearch/VisMa#145]
### Todo:
- ~Modify **gui/plotter.py** to plot both 2D/3D plots for some functions.~ (Fixed by #149 )
- Add support for single variable equations plots(Ex: `x = 1`, `x^2 = 4`).
### Example:
`x^2 + y^2 = 25` can be plotted in both 2D plot(a circle) and 3D plot(a cylinder). Currently this only plotted in 2D.

[This](https://github.com/aerospaceresearch/visma/blob/1971c7ae17688c30f105dd760b8058091778b334/visma/gui/plotter.py#L40-L49
) decides the dimension of the plot. Modify **gui/plotter.py** to plot in both figures.

**Comment by gr8geek** [comment]
So we have to plot the contour line of the function.

**Comment by gr8geek** [comment]
![image](https://user-images.githubusercontent.com/41500702/54084181-89843400-4353-11e9-9ebb-3e94e435ae79.png)

Do we have to plot something like this

**Comment by 8hantanu** [comment]
In the GUI there are two plot tabs(2D and 3D). We have to update the plot figures in both the tabs.
Following should be the expected output for `x^2 + y^2 = 25`.

2D plot tab |  3D plot tab
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/19494743/54084805-72494480-435b-11e9-878e-b7f8fc077b87.PNG" alt="2D" width="250"/> | <img src="https://user-images.githubusercontent.com/19494743/54084808-79705280-435b-11e9-9541-5714ebd89d17.PNG" alt="3D" width="250"/>

**Comment by abhinavsagar** [comment]
@8hantanu  Are you working on this.If not i am willing to. Please inform me regarding this.

**Comment by mayankDhiman** [comment]
Fixed by #198.
