### ISSUE TITLE
Adding modules for Expression simplification

### ISSUE THREAD

**Issue by mayankDhiman** [aerospaceresearch/VisMa#169]
**Problem:** Certain expressions like `(x+y)^2`, `(x^2 + xy + 1)*(x + y)`, `(x + y)^3` etc. are not simplified by VisMa.

**Solution:** The problem can be solved by writing a method `expressionSimplification` inside the _Expression Class_. Whenever we get an expression while tokenizing input equation, this function can be called. 

**Pre-requisites**: This would be easier to do once the _Simplify_ modules have been refactored. 

**Related issues**: #142, #141

**Comment by Alii-Khaled** [comment]
or by using __pow__ operator overloading of Expression Class right ?!

**Comment by Alii-Khaled** [comment]
and __Mult__ operator overloading too. 😂

**Comment by mayankDhiman** [comment]
Yes, as per me.
After overloading operators like **pow**, **mult** etc, we will include these inside _expressionSimplification_ method of _Expression Class_. And then call that method when tokens are instances of _Expression Class_.

**Comment by Alii-Khaled** [comment]
yup, exactly. 👍

**Comment by mayankDhiman** [comment]
Fixed by #199
