### ISSUE TITLE
gui crashes for some input while graph platter is enabled

### ISSUE THREAD

**Issue by subhani92** [aerospaceresearch/VisMa#170]
GUI crashes while graph-platter is enabled for some input like (x+y)^2=10(some constant)
error showing on terminal like this:-
![Screenshot from 2019-04-03 01-17-37](https://user-images.githubusercontent.com/33460354/55431542-71987c80-55ae-11e9-88a8-1477eb362bc6.png)

**Comment by Alii-Khaled** [comment]
Can you be more specific ?! what exactly the input that caused that crash ?!

**Comment by subhani92** [comment]
@Alii-Khaled  when clicking visma->simplyfy 
This crash doesn't occur when Graph platter opiton is unchecked.

**Comment by Alii-Khaled** [comment]
aha fine, so what was the input Equation you used in the application ?!

**Comment by subhani92** [comment]
@Alii-Khaled  It was (x+y)^2=10, note that it is working fine for this input x^2 + y^2 + 2xy =10 (2D graph was also plotted)

**Comment by Alii-Khaled** [comment]
ahaa, as mentioned in #169  the project have some bugs dealing with expressions raised to an integer power.

**Comment by subhani92** [comment]
@Alii-Khaled I would like to work on this issue, kindly guide me to fix this.

**Comment by Alii-Khaled** [comment]
Sorry I closed internet to study for an exam.
look I think you should work on another bug, because this one will be solved by default when Simplify Module got reworked.
