### ISSUE TITLE
Power gets subtracted from right value 

### ISSUE THREAD

**Issue by subhani92** [aerospaceresearch/VisMa#171]
As shown in below (x-y)^2=10 is converted into x-y-8=0. Power is subtracted from right value-
This issue occur when using braces i.g. (), because this expression (X)^2=10 is simplified as x-8=0.
While This is fine x^2=10.
![Screenshot from 2019-04-03 01-08-49](https://user-images.githubusercontent.com/33460354/55431986-642fc200-55af-11e9-9494-642101c143d2.png)

**Comment by sachinam1397** [comment]
I want to work on this issue . But can you tell me some more test cases.

**Comment by sachinam1397** [comment]
Can you assign me for this issue?

**Comment by mayankDhiman** [comment]
Fixed with Expression Simplification Module
