### ISSUE TITLE
Coefficient Optimization

### ISSUE THREAD

**Issue by soumyashaw** [aerospaceresearch/VisMa#246]
It shows the coefficient as float by default but will make more sense and realistic if it shows the coefficient without decimal is an integer.
Eg: 
now -> 2.0x + 3.0y + 2.3z
after optimization -> 2x + 3y + 2.3z

**Comment by rudrajit1729** [comment]
Can I work on it?

**Comment by rudrajit1729** [comment]
Can this be assigned to me @soumyashaw ?

**Comment by soumyashaw** [comment]
I don't have the assiging right @rudrajit1729 . You are free to proceed and create a Pull Request!

**Comment by rudrajit1729** [comment]
Which part of the code does this optimization require? Could you tell me on which part of the source code you need this optimization?

**Comment by rudrajit1729** [comment]
Could you provide me the link to the source code related to this particular issue @soumyashaw ?

**Comment by mayankDhiman** [comment]
In my opinion, it seems better if integers are represented as it is. Closing the issue for now, if there is a strong reason why this should be done, I will re open it.
