### ISSUE TITLE
Restructure code for I/O, probably create classes for each type of input

### ISSUE THREAD

**Issue by sidkothiyal** [aerospaceresearch/VisMa#28]

**Comment by arnab1896** [comment]
@sidkothiyal  @hornig 
Can i get this assigned to myself?

**Comment by sidkothiyal** [comment]
Hey @arnab1896,
Sure! 
The task will involve creating different modules/classes for different types of input. The need for this is really obvious, if we wish to expand the input styles for VisMa, classes will be really helpful. 
During my Gsoc I learnt something more important than coding, that is planning. Planning before starting to code decreases development time considerably and gives you a direction. 
I think we should have a separate module for each type of text input i.e generic maths input and latex. We can also combine all text based modules into one, but I think that'll make it complex. Also you can work around with the GUI of VisMa if you wish to.
Throw your ideas at me, it'll be great to have a discussion and listen to your side.
