### ISSUE TITLE
Integration and derivative module 

### ISSUE THREAD

**Issue by sidkothiyal** [aerospaceresearch/VisMa#32]

**Comment by ayush9398** [comment]
is this issue available? and also, what is this about?

**Comment by 8hantanu** [comment]
**To do**:
Add integration and derivation support for different Functions

**Prereq**:
Implementing the integration and derivatives methods will be simpler after the update of _Expression_ class(#141) and **simplify** module(#142).

**Expected outcome**:
- Add differentiate and integrate methods to all _Function_ classes (#143)
- Add algorithms like differentiation product-rule and integration by-parts
- Add unittests for  the above algorithms

**Comment by mayankDhiman** [comment]
Fixed by #209
