### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by 8hantanu** [aerospaceresearch/VisMa#62]
Create a CLI for visma. A query like **`simplify(x + x = 1 - y)`** should output as follows:
``` bash
$ visma
>>> simplify(x + x = 1 - y)
INPUT: x + x = 1 - y
OPERATION: simplify
OUTPUT: 2x - 1 + y = 0
STEPS: 
   x + x = 1 - y
⇒  2x = 1 - y                (Adding x and x)
⇒  2x - 1 + y = 0            (Moving rest of the terms to LHS)
>>> ...
```

**Comment by gr8geek** [comment]
Hello Shantanu,
I would like to work on the command line interface feature.
I would also like to add matrix and capabilities to visma in command line interface.

**Comment by 8hantanu** [comment]
@pratyushharsh9000 Sure. Fork the dev branch, make yourself familiar with the code base and read [this](https://github.com/aerospaceresearch/visma/wiki/Guidelines) before making a PR. If you need help and want to communicate further use the [chat](https://gitter.im/aerospaceresearch/VisMa). Cheers.

**Comment by lopuka** [comment]
Hi,I'm new and I would like to contribute,can someone get me started???

**Comment by abhishekti7** [comment]
@lopuka Head over to the projects tab for the current objectives.

**Comment by ZER-0-NE** [comment]
@8hantanu are we still looking to tackle this with the click module?

**Comment by 8hantanu** [comment]
@ZER-0-NE Yes. @mayankDhiman has created a nice simple CLI. But we still need support for input history and navigation using arrow keys which is present by default in click or [some other CLI library](https://realpython.com/comparing-python-command-line-parsing-libraries-argparse-docopt-click/).

**Comment by mayankDhiman** [comment]
Yep! It misses many features yet.

**Comment by mayankDhiman** [comment]
More improvements (or new features) in CLI will be added as the need arises. As of now, we have a simple & robust CLI, hence this issue is closed.
