### ISSUE TITLE
GUI exits abruptly when encountered errors

### ISSUE THREAD

**Issue by abhishekti7** [aerospaceresearch/VisMa#86]
Errors such as TypeError, Geometry-related errors etc. should be caught and displayed in a seperate area below the already existing dynamic quick solver.

**Comment by ZER-0-NE** [comment]
What kind of geometry related errors? Can you post an eg.?

**Comment by abhishekti7** [comment]
![capture](https://user-images.githubusercontent.com/32027962/50533294-e215a480-0b4c-11e9-9764-d0aa3f0dd463.PNG)

**Comment by ZER-0-NE** [comment]
How do I reproduce this bug?
