### ISSUE TITLE
Duplicate history 

### ISSUE THREAD

**Issue by he1l0world** [aerospaceresearch/VisMa#89]
![duplicate](https://user-images.githubusercontent.com/27997963/50535091-457ae480-0b03-11e9-8457-430b2c4ab3f6.png)
![duplicate2](https://user-images.githubusercontent.com/27997963/50535148-0d27d600-0b04-11e9-8c89-f4a6a6075457.png)
I just wrote a few equations, but the second time I opened the Visma, there are thousands of duplicated histories. It seems like it will double every time it opens.

**Comment by he1l0world** [comment]
![duplicate](https://user-images.githubusercontent.com/27997963/50535164-2df02b80-0b04-11e9-93e4-6ad6dd954b63.png)

**Comment by 8hantanu** [comment]
This issue is fixed in the dev branch. I think you are building from the main branch(refer [this](https://github.com/aerospaceresearch/visma/wiki/Guidelines)). If not, can you mention the equations/steps which reproduce the above error.

**Comment by he1l0world** [comment]
okay sorry I didn't notice that
