### ISSUE TITLE
Crash when I type list

### ISSUE THREAD

**Issue by he1l0world** [aerospaceresearch/VisMa#91]
![image](https://user-images.githubusercontent.com/27997963/50556336-0381a800-0c95-11e9-8468-5e541188c5be.png)
![image](https://user-images.githubusercontent.com/27997963/50556338-09778900-0c95-11e9-885f-6ad14663b586.png)
I'm trying to type equation like 99+(x+2), but when I was trying to type ')' then it crashed.

**Comment by ZER-0-NE** [comment]
I believe this was solved in #71.
EDIT: No

**Comment by he1l0world** [comment]
@ZER-0-NE This issue is that it will crash if we type parentheses in an equation.

**Comment by Rhitabrat** [comment]
> I believe this was solved in #71.

This issue is not solved.

**Comment by mayankDhiman** [comment]
Issue was solved with latest improvements.
As evident in screenshot:
![image](https://user-images.githubusercontent.com/32799055/52566152-055f8f00-2e2f-11e9-8a8b-449229cb02f1.png)
I  think it can be safely closed now
