### ISSUE TITLE
“Add Equation” will cause crash

### ISSUE THREAD

**Issue by he1l0world** [aerospaceresearch/VisMa#93]
![image](https://user-images.githubusercontent.com/27997963/50569405-50ab5b80-0d21-11e9-9d0e-b48fa51f0397.png)
![image](https://user-images.githubusercontent.com/27997963/50569503-d6300b00-0d23-11e9-9598-9e36909dd41f.png)

When I tried to add an empty file twice, then it will crash. The following are my guess:

> the first time it will execute the first if statement and pop the equation[0]. However, when it keeps executing the second if statement, the equation will still be an empty list because of the empty file.
> the second time when it executes the first if statement, it will case "index out of range".

The solution I thought was, if the user chooses an empty file then it will cause a warning and stop executing the following statement.

**Comment by he1l0world** [comment]
I would like to solve this issue.

**Comment by he1l0world** [comment]
I've solved this issue and it works fine on my computer. Also, I tested all the test modules.

**Comment by 8hantanu** [comment]
Can you make a PR?

**Comment by he1l0world** [comment]
@8hantanu Sure. Could you please review the pull request. Then I can create a new PR.

**Comment by 8hantanu** [comment]
I don't see any file changes in #92. I think you forgot to commit your local changes.

**Comment by he1l0world** [comment]
Oh, maybe I need to create a new PR. Thank you.
